# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# use_frameworks!

target 'COVIDTexas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for webscraping
  pod 'SwiftSoup'
  pod 'Charts'
  pod 'Kingfisher', '~> 5.0'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'COVIDTexasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'COVIDTexasUITests' do
    # Pods for testing
  end

end
